apiVersion: v1
kind: Service
metadata:
  name: k8s-todoservice
spec:
  selector:
    app: todoapp
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 3000 # the port of todoapp in container
      port: 3000 # the port map to Service from targetPort
      nodePort: 30300 # the port map to Node from service port